import Head from "next/head";
import Header from "./components/header";
import Projects from "./components/projects";
import Services from "./components/services";
import Certification from "./components/certification";
import Footer from "./components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>OluKayode Soliu- The Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Services></Services>
      <Projects></Projects>
      <Certification></Certification>
      <Footer></Footer>
    </>
  );
}
